name: Deploy MkDocs

on:
  push:
    branches:
      - main  

permissions:
  contents: write  
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs mkdocs-material
          # Se você tiver um requirements.txt, pode usar:
          # pip install -r requirements.txt

      - name: Build e Deploy no GitHub Pages
        run: |
          mkdocs gh-deploy --force --clean --remote-branch gh-pages
